bool plan_only
bool constrain_hand_orientation

string left_link_name
geometry_msgs/Pose left_end_eff
trajectory_msgs/JointTrajectory left_trajectory

string right_link_name
geometry_msgs/Pose right_end_eff
trajectory_msgs/JointTrajectory right_trajectory
---
int32 error_code
int32 FAIL=0
int32 SUCCESSFUL=1
---


